### ISSUE TITLE
Mounting /app as volume to host

### ISSUE THREAD

**Issue by ethanopp** [khannajai/dash-nginx-uwsgi-docker#2]
A little new to docker so apologies for the noobish question in advance...but is it possible to mount the /app dir to the host so I can edit files locally?

I'm trying to do something like this (below) but the /app directory keeps coming up empty when the last two lines where I mount the volume are included in my docker-compose 

***Dockerfile***
```
FROM tiangolo/uwsgi-nginx-flask:python3.6
LABEL maintainer="maintainer"
RUN git clone https://XXX:XXX@bitbucket.org/XXX/fitness.git
RUN pip install -U pip && pip install -r ./fitness/requirements.txt
ENV NGINX_WORKER_PROCESSES auto
```

***Docker Compose***
```  
  fitly:
    build:
      context: ./dockercontrol-master
      dockerfile: fitly-dockerfile
    container_name: fitly
    depends_on:
      - mariadb
    ports:
      - "8050:8050"
    environment:
      - PUID=1001
      - PGID=100
    volumes:
      - /share/CACHEDEV2_DATA/Container/Fitly:/app
```

Currently this puts the root dir of my repo into the root dir of the container... Ideally I'd want to just inject the contents of my repo right into the /app folder, this way every time i rebuild the container with compose, it automatically just pulls the latest files from the repo
